package.path = mud.luadir() .. "?.lua"

glob_tprintstr=require "tprint"
require "serialize"
util=require "utilities"
require "commands"
require "leaderboard"
require "arclib"
require "interpret"
require "scripting"
