#!/usr/bin/env bash
# Watchdog cron script - will ensure startup is running.

TOOLS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Configure timezone
TZRC="$HOME/.tzrc"

if [ -f "$TZRC" ]
then
    echo "Loading timezone config"
    source "$TZRC"
fi

STARTUP=`ps ux | grep startup | grep -v grep`
MUD=`ps ux | grep "aeaea 7000" | grep -v grep`

if [ -z "${STARTUP}" ]
then
    echo "startup not running"
    if [ "$MUD" = "" ]
    then
        echo "mud not running"
        echo `date` : Executing startup script
        cd $TOOLS_DIR
        csh ./startup &
    fi
fi

echo "watchdog done"
